package com.flybounce.sports.entity;
// Generated Jun 18, 2017 11:38:11 PM by Hibernate Tools 3.4.0.CR1

/**
 * Members generated by hbm2java
 */
public class Members implements java.io.Serializable {

	private MembersId id;
	private String memberName;
	private int memberPhone;
	private String membershipPlan;
	private String membersNoHours;
	private int memberStartTime;
	private String memberPaid;
	private String memberPaymentMthd;
	private String memberPaymentRef;
	private String memberSport;

	public Members() {
	}

	public Members(MembersId id, String memberName, int memberPhone, String membershipPlan, int memberStartTime,
			String memberPaid, String memberPaymentMthd, String memberPaymentRef, String memberSport) {
		this.id = id;
		this.memberName = memberName;
		this.memberPhone = memberPhone;
		this.membershipPlan = membershipPlan;
		this.memberStartTime = memberStartTime;
		this.memberPaid = memberPaid;
		this.memberPaymentMthd = memberPaymentMthd;
		this.memberPaymentRef = memberPaymentRef;
		this.memberSport = memberSport;
	}

	public Members(MembersId id, String memberName, int memberPhone, String membershipPlan, String membersNoHours,
			int memberStartTime, String memberPaid, String memberPaymentMthd, String memberPaymentRef,
			String memberSport) {
		this.id = id;
		this.memberName = memberName;
		this.memberPhone = memberPhone;
		this.membershipPlan = membershipPlan;
		this.membersNoHours = membersNoHours;
		this.memberStartTime = memberStartTime;
		this.memberPaid = memberPaid;
		this.memberPaymentMthd = memberPaymentMthd;
		this.memberPaymentRef = memberPaymentRef;
		this.memberSport = memberSport;
	}

	public MembersId getId() {
		return this.id;
	}

	public void setId(MembersId id) {
		this.id = id;
	}

	public String getMemberName() {
		return this.memberName;
	}

	public void setMemberName(String memberName) {
		this.memberName = memberName;
	}

	public int getMemberPhone() {
		return this.memberPhone;
	}

	public void setMemberPhone(int memberPhone) {
		this.memberPhone = memberPhone;
	}

	public String getMembershipPlan() {
		return this.membershipPlan;
	}

	public void setMembershipPlan(String membershipPlan) {
		this.membershipPlan = membershipPlan;
	}

	public String getMembersNoHours() {
		return this.membersNoHours;
	}

	public void setMembersNoHours(String membersNoHours) {
		this.membersNoHours = membersNoHours;
	}

	public int getMemberStartTime() {
		return this.memberStartTime;
	}

	public void setMemberStartTime(int memberStartTime) {
		this.memberStartTime = memberStartTime;
	}

	public String getMemberPaid() {
		return this.memberPaid;
	}

	public void setMemberPaid(String memberPaid) {
		this.memberPaid = memberPaid;
	}

	public String getMemberPaymentMthd() {
		return this.memberPaymentMthd;
	}

	public void setMemberPaymentMthd(String memberPaymentMthd) {
		this.memberPaymentMthd = memberPaymentMthd;
	}

	public String getMemberPaymentRef() {
		return this.memberPaymentRef;
	}

	public void setMemberPaymentRef(String memberPaymentRef) {
		this.memberPaymentRef = memberPaymentRef;
	}

	public String getMemberSport() {
		return this.memberSport;
	}

	public void setMemberSport(String memberSport) {
		this.memberSport = memberSport;
	}

}
